# define environment variables here as a map of key: value
env:
  SELDON_LOG_LEVEL: DEBUG

model:
  name: seldon-model-server
  # For more types see
  # https://docs.seldon.io/projects/seldon-core/en/latest/servers/overview.html
  type: SKLEARN_SERVER
  uri: gs://news_classifier/model
